import { motion } from "framer-motion";

const TermsPage = () => (
  <div className="container mx-auto px-6 py-24">
    <motion.div
      className="mx-auto max-w-3xl"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <h1 className="text-4xl font-bold mb-2 gradient-text">Terms & Conditions</h1>
      <p className="text-sm text-muted-foreground mb-12">Last updated: April 12, 2026</p>

      <div className="space-y-8 text-muted-foreground leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
          <p>By accessing and using eliteiq.tech ("the Service"), you agree to be bound by these Terms & Conditions. If you do not agree with any part of these terms, you must not use the Service.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
          <p>eliteiq.tech is an AI-powered metadata generation tool for stock content creators. The Service analyzes uploaded images and generates optimized titles, descriptions, and keywords for multiple stock photography platforms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">3. User Accounts</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You must provide accurate and complete information during registration</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials</li>
            <li>You must notify us immediately of any unauthorized use of your account</li>
            <li>One license key is intended for use by a single individual unless otherwise specified by your plan</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">4. License & Usage</h2>
          <p className="mb-3">Upon purchase, you receive a non-exclusive, non-transferable license to use the Service according to your plan:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li><span className="text-foreground font-medium">Starter:</span> Limited daily processing quota, single device activation</li>
            <li><span className="text-foreground font-medium">Creator:</span> Increased quota, up to 2 device activations</li>
            <li><span className="text-foreground font-medium">Pro:</span> Higher quota, up to 3 device activations</li>
            <li><span className="text-foreground font-medium">Studio:</span> Maximum quota, up to 5 device activations</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">5. Intellectual Property</h2>
          <p>You retain all rights to images you upload. The metadata generated by our Service is provided for your use and does not constitute our intellectual property claim over your content. The Service itself, including its design, code, and AI models integration, remains our intellectual property.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">6. Prohibited Use</h2>
          <p className="mb-3">You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Reverse engineer, decompile, or disassemble the software</li>
            <li>Share, resell, or redistribute your license key</li>
            <li>Use automated bots or scripts to abuse the Service</li>
            <li>Upload illegal, harmful, or infringing content</li>
            <li>Attempt to bypass usage limits or security measures</li>
            <li>Use the Service to generate misleading or fraudulent metadata</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">7. AI-Generated Content</h2>
          <p>The metadata generated by our AI models is provided on an "as-is" basis. While we strive for accuracy and relevance, we do not guarantee that generated metadata will result in specific search rankings or sales performance on any platform. You are responsible for reviewing and approving generated metadata before submission.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">8. Service Availability</h2>
          <p>We aim for high uptime but do not guarantee uninterrupted access. We reserve the right to modify, suspend, or discontinue any part of the Service with reasonable notice. Scheduled maintenance will be communicated in advance when possible.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">9. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, eliteiq.tech shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">10. Termination</h2>
          <p>We reserve the right to suspend or terminate your access if you violate these Terms. Upon termination, your license will be deactivated and you will lose access to premium features. Provisions that by their nature should survive termination will remain in effect.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">11. Changes to Terms</h2>
          <p>We may revise these Terms at any time. Material changes will be communicated via email or in-app notification. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">12. Contact Us</h2>
          <p>For questions about these Terms & Conditions, contact us at <a href="mailto:support@eliteiq.tech" className="text-primary hover:underline">support@eliteiq.tech</a>.</p>
        </section>
      </div>
    </motion.div>
  </div>
);

export default TermsPage;
